ui: tape
browserify:
  - transform:
      name: babelify
  - options:
      extensions:
        - .jsx
browsers:
  - name: chrome
    version: 43..latest
  - name: firefox
    version: 38..latest
  - name: safari
    version: 7..latest
  - name: ie
    version: 9..latest
  - name: opera
    version: 11..latest
  - name: iphone
    version: [7, 8, latest]
  - name: android
    version: 4.3..latest
