name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: ['latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Lint
        run: |-
          npm run format:check;
          npm run lint;

      - name: Test
        run: |-
          npm run test:coverage;
          npm run test:types;

      - name: Upload coverage to Codecov
        # https://github.com/marketplace/actions/codecov
        uses: codecov/codecov-action@v2

      - name: Build # Tests to see if a build can succeed
        run: npm run build

  e2e:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [chrome, firefox]
    timeout-minutes: 20
    container:
      # https://hub.docker.com/r/cypress/browsers/tags
      # NOTE: at least Chrome 102 is required for testing `inert` attribute support
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001 --shm-size=2g # @see https://github.com/cypress-io/github-action/issues/104#issuecomment-666047965
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test E2E
        # https://github.com/cypress-io/github-action
        # https://github.com/cypress-io/code-coverage
        uses: cypress-io/github-action@v5 # will run all tests found per cypress.config.js
        with:
          start: npm run start
          browser: ${{ matrix.browser }}
